import Head from 'next/head'
import Image from 'next/legacy/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {BsAlignCenter, BsMoonStarsFill} from 'react-icons/bs'
import {AiFillGithub, AiFillLinkedin, AiFillYoutube, AiFillHeart} from 'react-icons/ai'
import {IoIosPaper} from 'react-icons/io'
import chess from "../public/chessAI.png"
import avatar from "../public/avatar.png"
import vaccum from "../public/vaccum_robot.png"
import minesweeper from "../public/minesweeper.png"
import spotify from "../public/spotify.jpg"
import metropolIA from "../public/metropolIA.png"
import monnAI from "../public/monnAI.png"
import unity from "../public/unity.png"

import { useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Louise Lizé Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Portfolio</h1>
            
            <ul className='flex items-center'>
              <li>
                <BsMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li>
                <a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>
                  Resume
                </a>
                </li>
            </ul>

          </nav>

          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'> Louise Lizé</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'> Computer Science Student</h3>

            <div className='relative mx-auto bg-gradient-to-b from-neutral-500 rounded-full w-40 h-40 mt-10 overflow-hidden md:h-70 md:w-70'>
              <Image src={avatar} alt="" layout='fill' objectFit='cover'/>
            </div>

            <p className='text-md py-5 leading-8 text-gray-800 md:text-xxl max-w-xxl mx-auto dark:text-gray-400'>
              {/*Actuellement en double diplomation ingénieurie informatique à <a href='www.utc.fr' target="_blank" rel="noreferrer" className='text-teal-600'>l'UTC</a> et
              en maîtrise informatique à <a href='www.uqac.ca' target="_blank" rel="noreferrer" className='text-teal-600'>l'UQAC</a>, je suis à la recherche d'un 
              un <b>projet de fin d'études de six mois</b>, dès septembre 2023. Le stage de mes rêves serait plutôt orienté intelligence artificielle et science des données.
              Idéalement, j'aimerais l'effectuer au Canada, et plus particuliérement à Montréal.
              <br/><br/>
  Si mon profil vous intéresse, je vous invite à me contacter ! ☺*/}

              My name is Louise Lizé, and I am a computer science student engineer with a specialization in AI and Data Science 📈.

Although I am originally studying at the French engineering university UTC, I am currently pursuing a double degree program at UQAC in Canada, which has allowed me to expand my horizons and gain a unique perspective on my field of study.

As I look ahead to my future career, I am eager to gain industry experience through a 6-month internship starting in September 2023, with a preference for opportunities located in Montreal. However, I am also open to exploring opportunities elsewhere in the world. 🔭

On this platform, you can explore a selection of my favorite projects, both those I completed during my studies at school and those I pursued independently outside of the classroom. 💻

Please feel free to explore my repositories and connect with me on LinkedIn!
            </p>
          </div>


          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <a href='https://www.linkedin.com/in/louise-lize/' target="_blank" rel="noreferrer">
              <AiFillLinkedin/>
            </a>
            <a href='https://github.com/louiselize' target="_blank" rel="noreferrer">
              <AiFillGithub/>
            </a>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'> Portfolio </h3>
            
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              During my time in school, I worked on multiple computer science projects that focused on three areas: <span className='text-teal-500'> AI and data science</span>, <span className='text-teal-500'>web programming</span>, and <span className='text-teal-500'>video game development</span>. Through these experiences, I gained a wealth of knowledge and discovered complementary aspects among the three fields.
            </p>

          </div>

          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <h3 className='mb-5 text-4xl text-gray-800 dark:text-white'>
                Artificial Intelligence and Data Science
              </h3>
              
              <h5 className='text-3xl text-teal-600 dark:text-teal-400 font-medium pt-7 pb-5'>
                Intelligent Agent
              </h5> 
              
              <div className=' flex flex-wrap justify-center gap-14 lg:gap-20'>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={chess} className="rounded-lg object-cover" layout="responsive"/>
                              <div className="relative w-full p-4 bg-white dark:bg-gray-600">
                                <a href='https://github.com/louiselize/ChessAI' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-8 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="mb-2 mt-2 dark:text-white text-xl font-medium text-gray-800">
                                      Chess AI
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                      IA capable of playing chess
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Java
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #MinMax
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #AlphaBeta
                                      </div>
                                  </div>
                              </div>
                </div>
                
                
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={vaccum} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 bg-white dark:bg-gray-600">
                                <a href='https://github.com/louiselize/VacuumAI' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-8 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                  <p className="mb-2 mt-2 dark:text-white text-xl font-medium text-gray-800">
                                      Vaccum Cleaner AI
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                      Simulation of a cleaning robot in a castle
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #InformedSearch
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #NonInformedSearch
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #BDI
                                      </div>
                                  </div>
                              </div>
                </div>
                        
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={minesweeper} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <a href='https://github.com/louiselize/minesweeperAI' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-8 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                  <p className="mb-2 mt-2 text-xl font-medium dark:text-white text-gray-800">
                                      Minesweeper AI
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  IA able to play minesweeper
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Python
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #SATSolver
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #LogicProgramming
                                      </div>
                                  </div>
                              </div>
                </div>


              </div>

              <h5 className='text-teal-600 dark:text-teal-400 text-3xl font-medium pt-7 pb-5'>
                Machine Learning (without Deep Learning)
              </h5> 
              
              <div className=' flex gap-14 lg:gap-20 justify-center flex-wrap'>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={spotify} className="rounded-lg object-cover" layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-red-500 rounded-full left-12 -top-6">
                                  <AiFillHeart width="18"  height="18" fill="currentColor" className="w-5 h-5 mx-auto text-white"/>
                              </button>
                                <a href='https://github.com/louiselize/SpotifyDataAnalysis' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-12 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="dark:text-white mt-2 mb-2 text-xl font-medium text-gray-800">
                                      Spotify Data Analysis
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                    Spotify&apos;s data exploration using both supervised and unsupervised learning methods
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Python
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #Classification
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #SupervisedLearning
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #NonSupervisedLearning
                                      </div>
                                  </div>
                              </div>
                </div>
                
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={metropolIA} className="rounded-lg object-cover" layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                  <p className="dark:text-white mt-2 mb-2 text-xl font-medium text-gray-800">
                                      IA Serious Game
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                      Serious game project designed to introduce high school students to the exciting world of machine learning
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Unity
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #SciencePopularization
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #MachineLearning
                                      </div>
                                  </div>
                              </div>
                </div>
              </div>



              <h5 className='text-teal-600 dark:text-teal-400 text-3xl font-medium pt-7 pb-5'>
                Deep Learning
              </h5> 
              
              <div className='flex flex-wrap justify-center gap-14 lg:gap-20'>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={monnAI} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                
                                <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      Currency forecast
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                    Predict the EUR/CAD exchange rate using machine learning techniques
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Python
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-red-200 rounded-2xl">
                                          #RNN
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-red-200 rounded-2xl">
                                          #LSTM
                                      </div>
                                  </div>
                              </div>
                </div>
                
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={unity} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                  <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      Unity Deep Learning
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                    Implement deep learning algorithms to create an intelligent enemy
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Unity
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-red-200 rounded-2xl">
                                          #NeuralNetworks
                                      </div>
                                  </div>
                              </div>
                </div>
              </div>

              {/* A JSX comment 
              <h5 className='text-3xl dark:text-white font-medium pt-7 pb-5'>
                Traitement des images
              </h5> 
              
              <div className=' flex flex-wrap lg:gap-16 lg:justify-self-auto'>

                <div className="w-64 m-auto overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={chess} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                
                                <p className="mb-2 text-xl font-medium dark:text-white text-gray-800">
                                      Détection d'objets
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                      Entourée les objets non rangés à partir d'une photo de référence
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Python
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #OpenCV
                                      </div>
                                  </div>
                              </div>
                </div>
                
              </div>

              



                    <p className='py-4'>
                      {" "}
                      <b>Apprentissage Machine</b> 
                        <br/> Classement des morceaux Spotify selon leur genre<a href='https://www.overleaf.com/read/kxncjbwnghvt' target='_blank'></a> 
                        <br/> Jeux sérieux pour faire apprendre l'Apprentissage Machine
                        <br/><span className='text-gray-600 italic font-thin'>  ACP, KNN, Random Forest, Naif Baysien, KMeans, Regression Logistique </span>

                    </p>

                    <p className='py-4'>
                      {" "}
                      <b>Apprentissage Profond</b> 
                        <br/> Prédicteur taux de change EUR/CAN <span className='text-gray-600 italic font-thin'> (en cours) </span>
                        <br/> Utilisation du Deep Learning dans le moteur de jeu Unity <span className='text-gray-600 italic font-thin'> (en cours) </span>
                        <br/><span className='text-gray-600 italic font-thin'>  RNN, LSTM</span>

                    </p>

                    <p className='py-4'>
                      {" "}
                      <b>Traitement des images</b> 
                        <br/> Classement des morceaux spotify selon leur genre
                        <br/><span className='text-gray-600 italic font-thin'> Masque </span>
                    </p>
                    <p className='py-4'>
                      {" "}
                      <b>Métaheuristiques</b> 
                        <br/> Découverte des algorithmes les plus utilisés
                        <br/><span className='text-gray-600 italic font-thin'> Algorithme de descente, Recuit Simulé, Tabou </span>
                    </p>
                    <p className='py-4'>
                      {" "}
                      <b>Autres</b> 
                        <br/> Cours de statistiques 
                        <br/> Projet de gestion de données 
                        <br/><span className='text-gray-600 italic font-thin'> SQL, PostgreSQL, PlantUML, estimation, tests d'hypothèses, analyse de la variance, régression linéaire, intervalle de confiance </span>
                    </p>
                  
                  <br></br>
                  
                  <p>
                    <h4 className='py-2 text-cyan-500'>
                    Projets Extra Scolaire (verif orthoooooo)
                  </h4>
                  <p className='py-1'>
                    • Hackaton IA : comprendre les dessins industriels par traitement des images
                  </p>
                  <p className='py-1'>
                    {" "}
                    • Membre d'OCIAN : club de compétitions de l'UQAC en IA et Jeux Vidéo
                  </p>
                  <p className='py-1'>
                    {" "}
                    • Tutrice en statistiques : pour les étudiants de l'UTC en difficulté
                  </p>
                  <br/>
                  <h4 className='py-2 text-teal-600'> Langages et librairies</h4>
                  <p className='text-gray-800 py-1'>R</p>
                  <p className='text-gray-800 py-1'>Python</p>
                  <p className='text-gray-800 py-1'>Scikit, Tensorflow</p>
                </p>
            </div>

          <div className='lg:flex gap-10 justify-center'>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700 dark:bg-opacity-80">
              <h3 className='text-lg dark:text-white font-medium pt-8 pb-2'>Jeux vidéo</h3>
              <p className='py-4 dark:text-white'>
                {" "}
                Conception et développement de jeux vidéo
                <br/><span className='text-gray-600 italic dark:text-white font-thin'>Unity 2D, C#</span>

              </p>
              <p className='py-4 dark:text-white'>
                {" "}
                Ajout de features sur le projet VR Victeams
                <br/><span className='text-gray-600 italic dark:text-white font-thin'>Unity, SteamVR, Oculus</span>
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <h3 className='text-lg font-medium pt-8 pb-2'>Développement web</h3>
              <p className='py-4'>
                {" "}
                Stage de 6 mois en tant que développeuse Full Stack chez Olvid
                <br/><span className='text-gray-600 italic font-thin'>Java, VueJS, Liquibase, SQL, GitLab</span>
              </p>

              <p className='py-4'>
                {" "}
                Projet personnel : CV site Web  
                <br/><span className='text-gray-600 italic font-thin'>VueJS, BoostrapVue</span>
              </p>
              
              <p className='py-4'>
                {" "}
                Projet interactif : simulation humoristique de la vie étudiante à l'UTC 
                <br/><span className='text-gray-600 italic font-thin'>Twine</span>
              </p>
            </div>

          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'> Portfolio </h3>
          
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. 3
              Proin vitae sapien quis urna suscipit <span className='text-teal-500'> bibendum </span> 
              non ut lacus. Donec in felis mi. Sed fringilla eleifend tortor, porta imperdiet ex imperdiet non. Praesent auctor eros in erat eleifend, et hendrerit eros congue. Mauris auctor mattis egestas. Curabitur in est sapien. Duis ut eros hendrerit, egestas turpis vitae, posuere mi. Donec eu interdum neque, sed imperdiet tellus. Phasellus enim elit, pellentesque accumsan congue sit amet, ullamcorper eget ante.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. 3
              Proin vitae sapien quis urna suscipit <span className='text-teal-500'> bibendum </span> 
              non ut lacus. Donec in felis mi. Sed fringilla eleifend tortor, porta imperdiet ex imperdiet non. Praesent auctor eros in erat eleifend, et hendrerit eros congue. Mauris auctor mattis egestas. Curabitur in est sapien. Duis ut eros hendrerit, egestas turpis vitae, posuere mi. Donec eu interdum neque, sed imperdiet tellus. Phasellus enim elit, pellentesque accumsan congue sit amet, ullamcorper eget ante.
            </p>

          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis/1/3'>
              <Image src={chess} className="rounded-lg object-cover" layout="responsive"/>
            </div>
            <div className='basis/1/3'>
              <Image src={chess} className="rounded-lg object-cover" layout="responsive"/>
            </div>
            <div className='basis/1/3'>
              <Image src={chess} className="rounded-lg object-cover" layout="responsive"/>
            </div>
            <div className='basis/1/3'>
              <Image src={chess} className="rounded-lg object-cover" layout="responsive"/>
            </div>*/}
          </div>
        </section>
  
      </main>
    </div>
  )
}
