import Head from 'next/head'
import Image from 'next/legacy/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {BsAlignCenter, BsMoonStarsFill} from 'react-icons/bs'
import {GoGraph} from 'react-icons/go'
import {HiMagnifyingGlass} from 'react-icons/hi2'
import {AiFillPlusSquare, AiFillGithub, AiFillLinkedin, AiFillYoutube, AiFillHeart, AiFillTrophy, AiOutlineLink,AiFillEye} from 'react-icons/ai'
import {FaDatabase, FaGraduationCap} from 'react-icons/fa'
import {IoIosPaper} from 'react-icons/io'
import {FcStatistics} from 'react-icons/fc'
import {MdVideogameAsset} from 'react-icons/md'
import chess from "../public/chessAI.png"
import avatar from "../public/avatar.png"
import vaccum from "../public/vaccum_robot.png"
import minesweeper from "../public/minesweeper.png"
import spotify from "../public/spotify.jpg"
import metropolIA from "../public/metropolIA.png"
import monnAI from "../public/monnAI.png"
import unity from "../public/unity.png"
import olvid from "../public/olvid.jpg"
import resume from "../public/resume.png"
import simulut from "../public/simulut.png"
import victeams from "../public/victeams.jpg"


import { useState } from 'react';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Louise Lizé Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Portfolio</h1>
            
            <ul className='flex items-center'>
              <li>
                <BsMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li>
                <a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>
                  Resume
                </a>
                </li>
            </ul>

          </nav>

          <div className='text-center p-4'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'> Louise Lizé</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'> Computer Science Student</h3>

            <div className='relative mx-auto bg-gradient-to-b from-neutral-500 rounded-full w-40 h-40 mt-10 overflow-hidden md:h-70 md:w-70'>
              <Image src={avatar} alt="" layout='fill' objectFit='cover'/>
            </div>

            <p className='text-md py-5 leading-8 text-gray-800 md:text-xxl max-w-xxl mx-auto dark:text-gray-400'>
              {/*Actuellement en double diplomation ingénieurie informatique à <a href='www.utc.fr' target="_blank" rel="noreferrer" className='text-teal-600'>l'UTC</a> et
              en maîtrise informatique à <a href='www.uqac.ca' target="_blank" rel="noreferrer" className='text-teal-600'>l'UQAC</a>, je suis à la recherche d'un 
              un <b>projet de fin d'études de six mois</b>, dès septembre 2023. Le stage de mes rêves serait plutôt orienté intelligence artificielle et science des données.
              Idéalement, j'aimerais l'effectuer au Canada, et plus particuliérement à Montréal.
              <br/><br/>
  Si mon profil vous intéresse, je vous invite à me contacter ! ☺*/}

              My name is Louise Lizé, and I am a computer science student engineer with a specialization in AI and Data Science 📈.

Although I am originally studying at French engineering university <a href='https://www.utc.fr/' target="_blank" rel="noreferrer" className='text-teal-600'>UTC</a>, I am currently pursuing a double degree program at <a href='https://www.uqac.ca/' target="_blank" rel="noreferrer" className='text-teal-600'>UQAC</a> in Canada, which has allowed me to expand my horizons and gain a unique perspective on my field of study.

As I look ahead to my future career, I am eager to gain industry experience through a 6-month internship starting in September 2023, with a preference for opportunities located in Montreal. However, I am also open to exploring opportunities elsewhere in the world. 🔭
<br></br>
On this platform, you can explore a selection of my favorite projects, completed during my studies at school and outside of the classroom. 💻
<br/><br></br>
Please feel free to explore my repositories and connect with me on LinkedIn!
            </p>
          </div>


          <div className='text-5xl flex justify-center gap-16 pb-16 text-gray-600 dark:text-gray-400'>
            <a href='https://www.linkedin.com/in/louise-lize/' target="_blank" rel="noreferrer">
              <AiFillLinkedin/>
            </a>
            <a href='https://github.com/louiselize' target="_blank" rel="noreferrer">
              <AiFillGithub/>
            </a>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'> Portfolio </h3>
            
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              During my time in school, I worked on multiple computer science projects that focused on three areas: <span className='text-teal-500'> AI and data science</span>, <span className='text-teal-500'>web programming</span>, and <span className='text-teal-500'>video game development</span>. Through these experiences, I gained a wealth of knowledge and discovered complementary aspects among the three fields.
            </p>

          </div>

          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <h3 className='mt-2 text-3xl font-extrabold leading-8 tracking-tight text-gray-900 sm:text-4xl dark:text-white'>
                Artificial Intelligence and Data Science
              </h3>
              
              <h5 className='my-4 text-indigo-600 dark:text-indigo-400 font-semibold tracking-wide uppercase text-xl pt-7 pb-5'>
                Intelligent Agent
              </h5> 
              
              <div className=' flex flex-wrap justify-center gap-14 lg:gap-20'>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={chess} className="rounded-lg object-cover" layout="responsive"/>
                              <div className="relative w-full p-4 bg-white dark:bg-gray-600">
                                <a href='https://github.com/louiselize/ChessAI' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-8 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="mb-2 mt-2 dark:text-white text-xl font-medium text-gray-800">
                                      Chess AI
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                      IA capable of playing chess
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Java
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #MinMax
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #AlphaBeta
                                      </div>
                                  </div>
                              </div>
                </div>
                
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={vaccum} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 bg-white dark:bg-gray-600">
                                <a href='https://github.com/louiselize/VacuumAI' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-8 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                  <p className="mb-2 mt-2 dark:text-white text-xl font-medium text-gray-800">
                                      Vaccum Cleaner AI
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                      Simulation of a cleaning robot in a castle
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #InformedSearch
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #NonInformedSearch
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #BDI
                                      </div>
                                  </div>
                              </div>
                </div>
                        
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={minesweeper} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <a href='https://github.com/louiselize/minesweeperAI' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-8 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                  <p className="mb-2 mt-2 text-xl font-medium dark:text-white text-gray-800">
                                      Minesweeper AI
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  IA able to play minesweeper
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Python
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #SATSolver
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-purple-200 rounded-2xl">
                                          #LogicProgramming
                                      </div>
                                  </div>
                              </div>
                </div>


              </div>

              <h5 className='my-4 text-indigo-600 dark:text-indigo-400 font-semibold tracking-wide uppercase text-xl pt-7 pb-5'>
                Machine Learning (without Deep Learning)
              </h5> 
              
              <div className=' flex gap-14 lg:gap-20 justify-center flex-wrap'>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={spotify} className="rounded-lg object-cover" layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-red-500 rounded-full left-12 -top-6">
                                  <AiFillHeart width="18"  height="18" fill="currentColor" className="w-5 h-5 mx-auto text-white"/>
                              </button>
                                <a href='https://github.com/louiselize/SpotifyDataAnalysis' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-12 -top-6">
                                  <AiFillGithub width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="dark:text-white mt-2 mb-2 text-xl font-medium text-gray-800">
                                      Spotify Data Analysis
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                    Spotify&apos;s data exploration using both supervised and unsupervised learning methods
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Python
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #Classification
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #SupervisedLearning
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #NonSupervisedLearning
                                      </div>
                                  </div>
                              </div>
                </div>
                
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={metropolIA} className="rounded-lg object-cover" layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                  <p className="dark:text-white mt-2 mb-2 text-xl font-medium text-gray-800">
                                      IA Serious Game
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                      Serious game project designed to introduce high school students to the exciting world of machine learning
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Unity
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #SciencePopularization
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-blue-200 rounded-2xl">
                                          #MachineLearning
                                      </div>
                                  </div>
                              </div>
                </div>
              </div>



              <h5 className='my-4 text-indigo-600 dark:text-indigo-400 font-semibold tracking-wide uppercase text-xl pt-7 pb-5'>
                Deep Learning
              </h5> 
              
              <div className='flex flex-wrap justify-center gap-14 lg:gap-20'>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={monnAI} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                
                                <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      Currency forecast
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                    Predict the EUR/CAD exchange rate using machine learning techniques
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Python
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-red-200 rounded-2xl">
                                          #RNN
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-red-200 rounded-2xl">
                                          #LSTM
                                      </div>
                                  </div>
                              </div>
                </div>
                
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={unity} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                  <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      Unity Deep Learning
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                    Implement deep learning algorithms to create an intelligent enemy
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Unity
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-red-200 rounded-2xl">
                                          #NeuralNetworks
                                      </div>
                                  </div>
                  </div>
              </div>           

            </div>


            <div className="container p-6 px-6 rounded-2xl bg-white dark:bg-gray-800">
    <div className="mb-2 text-center">
        <h2 className="text-indigo-600 dark:text-indigo-400 font-semibold tracking-wide uppercase text-xl pt-7 pb-5">
            Value-Added Features
        </h2>
    </div>
    <div className="flex flex-wrap mb-12 dark:text-white">
        <div className="w-full p-8 border-b md:w-1/2 md:border-r lg:w-1/3">
            <div className="flex items-center mb-6">
                <AiFillPlusSquare className='w-6 h-6 text-indigo-500'/>
                <div className="ml-4 text-xl">
                  Metaheuristics
                </div>
            </div>
            <p className="leading-loose text-gray-500 dark:text-gray-200 text-md">
              Exploration of Metaheuristic Algorithms: Genetic Algorithms, Simulated Annealing, Tabu Search, Hill Climbing, Ant Colony Optimization
            </p>
        </div>
        <div className="w-full p-8 border-b md:w-1/2 lg:w-1/3 lg:border-r">
            <div className="flex items-center mb-6">
                <AiFillEye className='w-6 h-6 text-indigo-500'/>
                <div className="ml-4 text-xl">
                    Computer Vision
                </div>
            </div>
            <p className="leading-loose text-gray-500 dark:text-gray-200 text-md">
            Image manipulation and transformation, familiarization with Artificial vision and image processing modules : NumPy, OpenCV, scikit-image, scikit-learn, TensorFlow, Keras.
            </p>
        </div>
        <div className="w-full p-8 border-b md:w-1/2 md:border-r lg:w-1/3 lg:border-r-0">
            <div className="flex items-center mb-6">
                <GoGraph className='w-6 h-6 text-indigo-500'/>
                <div className="ml-4 text-xl">
                    Statistic
                </div>
            </div>
            <p className="leading-loose text-gray-500 dark:text-gray-200 text-md">
              Advanced statistics course covering : estimation, hypothesis testing, analysis of variance, linear regression, and confidence intervals.
            </p>
        </div>
        <div className="w-full p-8 border-b md:w-1/2 lg:w-1/3 lg:border-r lg:border-b-0">
        <div className="flex items-center mb-6">
                <FaDatabase className='w-6 h-6 text-indigo-500'/>
                <div className="ml-4 text-xl">
                    Database
                </div>
            </div>
            <p className="leading-loose text-gray-500 dark:text-gray-200 text-md">
              Familiar with database conception and implementation with SQL, PostgreSQL, and PlantUML tools.
            </p>
        </div>
        <div className="w-full p-8 border-b md:w-1/2 md:border-r md:border-b-0 lg:w-1/3 lg:border-b-0">
            <div className="flex items-center mb-6">
                <AiFillTrophy className="w-6 h-6 text-indigo-500"/>
                <div className="ml-4 text-xl">
                    AI Competition
                </div>
            </div>
            <p className="leading-loose text-gray-500 dark:text-gray-200 text-md">
              Member of the UQAC AI competition team called OCIAN.
              Participation in AI Hackathon
            </p>
        </div>
        <div className="w-full p-8 md:w-1/2 lg:w-1/3">
            <div className="flex items-center mb-6">
                <FaGraduationCap className="w-6 h-6 text-indigo-500"/>
                <div className="ml-4 text-xl">
                  University Tutor
                </div>
            </div>
            <p className="leading-loose text-gray-500 dark:text-gray-200 text-md">
              University student job : tutor students who faced difficulties in advanced statistics course.
            </p>
        </div>
    </div>
              </div> 
          </div>

            
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <h3 className='mt-2 mb-4 text-3xl font-extrabold leading-8 tracking-tight text-gray-900 sm:text-4xl dark:text-white'>
                Web Development
              </h3>
              
              <div className='flex flex-wrap items-baseline justify-center gap-14 lg:gap-20'>
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={resume} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <a href='https://louiselize.github.io/#' target="_blank" rel="noreferrer">
                              <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-12 -top-7">
                                  <AiOutlineLink width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      Resume Website
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  I took on this project as my first personal venture, with the goal of improving my skills and having fun along the way.
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #VueJS
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #BootstrapVue
                                      </div>
                                      
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-amber-200 rounded-2xl">
                                          #PersonalProject
                                      </div>
                                  </div>
                              </div>
                </div>
                <div className="w-96 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={olvid} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <a href='https://olvid.io/faq/olvid-management-console/' target="_blank" rel="noreferrer">
                              <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-12 -top-7">
                                  <HiMagnifyingGlass width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                    Full Stack Developer Intern
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  <span className='text-gray-600 italic font-thin dark:text-gray-300'>  Sept. 2021 - Feb. 2022 </span>
                                    <br></br><br></br>
                                    <b>6-month</b> internship at <a href='https://olvid.io/en/' target="_blank" rel="noreferrer" className='text-blue-700 dark:text-blue-300'>Olvid</a>, french start-up specialized in providing highly secure messaging services. 
                                    <br></br>
                                    Creation of a web application for company admins. The app was designed to allow the administrators of Olvid&apos;s client companie to create and manage groups, add or remove workers, configure settings, restrict visibility, and revoke keys as needed.
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #VueJS
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Java
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #BootsrapVue
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #GitLab
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Liquibase
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Keycloak
                                      </div>
                                  </div>
                              </div>
                </div>
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={simulut} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <a href='http://www.utc.fr/si28/ProjetsUpload/P2021_si28p003/index.html' target="_blank" rel="noreferrer">
                              <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-12 -top-7">
                                  <AiOutlineLink width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                  <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      Simul&apos;UT
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  Creating an interactive and multimedia project. 
                                  Project within a <b>social sciences</b> framework rather than technical sciences.

                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Twine
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSS
                                      </div>
                                      <div className="text-xs mb-2 py-1.5 px-4 text-gray-600 bg-amber-200 rounded-2xl">
                                          #SocialSciences
                                      </div>
                                  </div>
                              </div>
                </div>
              </div>

            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <h3 className='mt-2 mb-4 text-3xl font-extrabold leading-8 tracking-tight text-gray-900 sm:text-4xl dark:text-white'>
                Video Games Development
              </h3>
              
              <div className='flex flex-wrap justify-center gap-14 lg:gap-20'>
                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                  <video src="ic06.mp4" autoPlay={true} loop muted className=""/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <a href='https://github.com/louiselize/God_s_Savior' target="_blank" rel="noreferrer">
                                  <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-8 -top-6">
                                  <MdVideogameAsset width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      God&apos;s Savior
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  Acquiring the skills and knowledge necessary to both design and implement a game, while also becoming proficient with Godot game engine.
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Godot
                                      </div>
                                      
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-orange-200 rounded-2xl">
                                          #RPG
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-orange-200 rounded-2xl">
                                          #ZeldaLike
                                      </div>
                                  </div>
                              </div>
                </div>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                          <Image src={victeams} className="rounded-lg object-cover"  layout="responsive"/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                              <a href='https://anr.fr/en/latest-news/read/news/virtual-reality-to-train-medical-experts-in-team-management-in-crisis-situations-the-anr-victeams-p/' target="_blank" rel="noreferrer">
                              <button aria-label="Go to article" type="button" className="absolute w-12 h-12 text-white bg-gray-700 rounded-full right-12 -top-7">
                                  <HiMagnifyingGlass width="20"  height="20" fill="currentColor" className="w-6 h-6 mx-auto text-white"/>
                                  </button>
                                </a>
                                <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      VICTEAMS VR Project
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  Implementing a new feature to medical professionals simulation in stressful and crisis situations. Create additional challenges by creating a size limit on the stock.
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #SteamVR
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Unity
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                  </div>
                              </div>
                </div>

                <div className="w-64 overflow-hidden shadow-lg rounded-2xl h-90 mb-8 dark:bg-gray-600">
                    <video src="amalgames.mp4" autoPlay={true} loop muted className=""/>
                              <div className="relative w-full p-4 dark:bg-gray-600 bg-white">
                                  <p className="dark:text-white mb-2 text-xl font-medium text-gray-800">
                                      Amalgames
                                  </p>
                                  <p className="text-xs dark:text-gray-300 text-gray-600">
                                  Acquiring the skills and knowledge necessary to both design and implement a game, while also becoming proficient with Unity game engine.
                                  </p>
                                  <div className="flex flex-wrap items-center mt-6 justify-starts">
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #Unity2D
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-green-200 rounded-2xl">
                                          #CSharp
                                      </div>
                                      <div className="text-xs mb-2 mr-2 py-1.5 px-4 text-gray-600 bg-orange-200 rounded-2xl">
                                          #Plateformer
                                      </div>
                                  </div>
                              </div>
                </div>
              </div>

            </div>

            
            <br></br>
          
        </section>
  
      </main>
    </div>
  )
}
